version: '3.0'

services:
  postgres:
    container_name: postgres_container
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - ./postgresFOLDER:/data/postgres # to choose your personal directory, change only the left path. 
    ports:
      - "5432:5432" # to choose your personal port, change only the left port.
    networks:
      - postgres

    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-base@didati2.it}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - ./pgadminFOLDER:/root/.pgadmin # to choose your personal directory, change only the left path.
    ports:
      - "5000:80"  # to choose your personal port, change only the left port.
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres: 
    driver: bridge

volumes:
    postgres:
    pgadmin:
